# Project
version=1.0.0
group=com.mrrockis.simplefullbright

# Common
minecraft_version=1.16.5
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server

# Fabric
fabric_version=0.42.0+1.16
fabric_loader_version=0.14.9

# Mod options
mod_name=Simple Fullbright
mod_author=MrRockis
mod_id=simplefullbright

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false